### ISSUE TITLE
Como puedo implementarlo

### ISSUE THREAD

**Issue by henrypandales** [jpcandioti/php-ws-afip#1]
Atento saludo, quiero implementar este codigo en mi sistema de facturación
http://chamansos.com/ecyberx
Usuario: henry
Clave: henry

Por favor escribeme al whatsapp +57 314 775 4208
que estoy un poco perdido

**Comment by jpcandioti** [comment]
Mil disculpas Henry, recién veo tu consulta. Avisame si aún puedo ayudarte, prometo estar más atento a las incidencias. Saludos!

**Comment by henrypandales** [comment]
Desde luego que si, claro
Te dejo mi WhatsApp , te pido el favor que cuando me escribas me hagas un recorderis

Mil gracias
________________________________

**Comment by henrypandales** [comment]
Si, la verdad es deseo mayor orientacion para implementarlo en mi sistema de facturacion y si por de paso tienes algo de geolocalizacion de pedidos similar a Uber 

mil gracias

**Comment by jpcandioti** [comment]
Hola Henry, no tendría problema de ayudarte, pero necesitaría que seas más preciso en la pregunta...

**Comment by jpcandioti** [comment]
¿Pudiste solicitar en AFIP los certificados de homologación para poder realizar pruebas sobre la API de AFIP?
En el README del proyecto hay enlaces a varios documentos oficiales de la AFIP que explican estos procedimientos.
Si ya tienes todo eso puedes probar de ejecutar los ejemplos que están en el README.

**Comment by henrypandales** [comment]
cual sera el link de AFIP ?

**Comment by henrypandales** [comment]
Bueno yo estoy en Colombia DIAN 
https://catalogo-vpfe-hab.dian.gov.co/User/PersonAuthentication

**Comment by jpcandioti** [comment]
No llego a entender bien... imagino que tendrás un sistema con clientes argentinos que necesiten facturar en la AFIP... sino es así esto no te va a servir. Esta librería cuenta con un README que explica estas cuestiones, quizás deberías analizar si realmente esto es lo que estás buscando implementar.

**Comment by henrypandales** [comment]
Mil gracias, debe seer como dices, pues la necesito para aprender a montarla API para DIAN Colombia oficina de impuestos

**Comment by jpcandioti** [comment]
Claro, no, entonces no te sirve. Saludos!
