### ISSUE TITLE
Array Iva 

### ISSUE THREAD

**Issue by lucasgonzz** [jpcandioti/php-ws-afip#2]
Hola, antes que nada, gracias por el aporte! Mi problema es el siguiente: En el array $invoice, indice 'FeCAEReq'=>'FeDetReq'=>'FECAEDetRequest'=>'Iva' cuando se tiene que especificar mas de un tipo de iva, tengo que usar el mismo indice "AlicIva" para los elementos dentro del array, alguna idea de como solucionarlo?
Desde ya muchas gracias!

**Comment by jpcandioti** [comment]
Hola Lucas, perdón la demora en responderte, recién veo el asunto. La verdad que no tengo claro este caso, por lo que no puedo ayudarte. La estructura de los métodos del WSFE es un punto muy específico que excede el ámbito de esta librería.

**Comment by jpcandioti** [comment]
Hola Lucas, perdón la demora en responderte, recién veo la incidencia.
La verdad que no tengo claro este caso, por lo que no puedo ayudarte. La estructura de los métodos del WSFE es un punto muy específico que excede el ámbito de esta librería.
Para estos casos creo que pueden servirte los ejemplos de Solicitar TA y de WSFE que están en el README.md. De esta forma podés hacer diferentes pruebas con la cuenta de homologación, extrayéndote de la complejidad del sistema dónde estés implementando la librería.
Cualquier otra consulta no dudes en abrir otra incidencia.
Saludos!
